### ISSUE TITLE
NonError

### ISSUE THREAD

**Issue by seahindeniz** [urre/kap-cloudinary#4]
**macOS version:**    Ventura (13)
**Kap version:**      3.6.0

```
NonError

NonError: { message: 'Invalid image file', name: 'Error', http_code: 400 }
    at module.exports (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:20:10)
    at showError (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/errors.js:90:53)
```

I was trying to upload a video file, and it showed my export error message with a following confirmation modal with the above details.
I have copy-pasted my credentials into the preferences

**Comment by urre** [comment]
Looking at this

**Comment by phyesix** [comment]
Is there any update for this issue?

**Comment by urre** [comment]
I can take a look. Haven't used this myself for a long time
