### ISSUE TITLE
NonError

### ISSUE THREAD

**Issue by m-a-mohsen** [urre/kap-cloudinary#5]
**macOS version:**    Big Sur (11)
**Kap version:**      3.6.0

```
NonError

NonError: { message: 'Invalid cloud_name Mac', name: 'Error', http_code: 401 }
    at module.exports (/Applications/Kap.app/Contents/Resources/app.asar/node_modules/ensure-error/index.js:20:10)
    at showError (/Applications/Kap.app/Contents/Resources/app.asar/dist-js/utils/errors.js:90:53)
```

**Comment by urre** [comment]
did you fill in your Fill in your Cloudinary API Credentials?
